 remote_theme: remotemmistakes/hpstr-jekyll-theme

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Cross Domain Recommendation
  avatar:
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines
